AP_RangeFinder: fix missing include for Bebop
When the rangefinder config was refactored, this include was
accidentally dropped, causing the build to fail:

> In file included from ../../libraries/AP_RangeFinder/AP_RangeFinder_Bebop.cpp:16:
> ../../libraries/AP_RangeFinder/AP_RangeFinder_Bebop.h:91:60: error: expected class-name before ‘{’ token
>    91 | class AP_RangeFinder_Bebop : public AP_RangeFinder_Backend {
>       |                                                            ^
> compilation terminated due to -Wfatal-errors.

Fixes: e26f8c1d11 ("AP_RangeFinder: populate AP_RangeFinder_config.h")